language: node_js
node_js:
  - "16"

cache:
  directories:
    - node_modules

install:
  - npm install

script:
  - npm run build --prod
  - npm run test --watch=false

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/web-protasks
  on:
    branch: master
