language: node_js
node_js:
  - "16"
dist: xenial
services:
  - xvfb

cache:
  directories:
    - node_modules

install:
  - npm install

script:
  - npm run build --prod
  - karma start --browsers Firefox --single-run

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/web-protasks
  on:
    branch: master
